import { expect, test } from "@playwright/test";

async function login(page: import("@playwright/test").Page) {
  await page.goto("/login");
  await page.getByLabel("Email").fill("operator@example.com");
  await page.getByRole("button", { name: "Send code" }).click();
  const statusText = await page.getByRole("status").textContent();
  const previewCode = statusText?.match(/\b\d{6}\b/)?.[0] ?? "";
  await page.getByLabel("Code").fill(previewCode);
  await page.getByRole("button", { name: "Verify & continue" }).click();
  await expect(page).toHaveURL(/\/engine$/);
}

test("live operator model assist applies a frame draft", async ({ page }) => {
  await page.route("**/api/operator/model", async (route) => {
    const request = route.request();
    expect(request.method()).toBe("POST");
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        mode: "draft_frame",
        model: "gpt-4.1-mini",
        outputText: "Structured frame draft generated by test route.",
        frameDraft: {
          text: "Decide whether to escalate a safety incident.",
          objective_type: "decide",
          domain: "safety",
          time_horizon: "short",
          key_uncertainty: "Whether the first report reflects a real critical signal.",
          constraints_hard: ["Maintain RED before BLUE sequencing."],
          constraints_soft: ["Minimize unnecessary disruption."],
          red_definition: "Missing a catastrophic incident.",
          blue_goals: "Protect users while avoiding unnecessary escalation.",
        },
      }),
    });
  });

  await login(page);
  await page.goto("/operator");
  await page.getByRole("button", { name: /Model Assist/i }).click();
  await page.getByLabel(/Model prompt/i).fill("Frame a safety escalation decision.");
  await page.getByRole("button", { name: /Draft Frame/i }).click();

  await expect(page.getByLabel(/Frame question/i)).toHaveValue(/Decide whether to escalate/);
  await expect(page.getByLabel(/Red channel definition/i)).toHaveValue(/catastrophic/);
});
